from strategy_spielstufe_auswählen import*

spielstufe_Startbildschirm.spielstufe_ausführen()
spielstufe_Namenseingabe.spielstufe_ausführen()
spielstufe_Heldenauswahl.spielstufe_ausführen()
spielstufe_Levelauswahl.spielstufe_ausführen()
spielstufe_Spielende.spielstufe_ausführen()